added my card with resources
Bauddhik-Geeks/Resource-Finder pull request #92
Opened 2022-10-16 07:47 UTC by palaksinghania05

2022-10-16 08:19 UTC, Nitesh-thapliyal requested changes

2022-10-16 08:19 UTC, Nitesh-thapliyal commented on index.html
> +                               title="Second Resource">A to Z of AWSt</a>
can you fix the typo "AWSt"

2022-10-17 15:59 UTC, palaksinghania05 commented
I have fixed the typo!

2022-10-18 01:48 UTC, Nitesh-thapliyal commented
@palaksinghania05 can you resolve the conflict

2022-10-21 18:45 UTC, closed without merging